# Generated by Django 4.2.3 on 2023-09-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sharedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
