# Generated by Django 4.2.6 on 2023-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_no_of_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('msgcontent', models.TextField()),
            ],
        ),
    ]
